[build]
  publish = "dist/"
  command = "npm run build"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = ".netlify/functions-internal/"

[dev]
  command = "npm start"
  port = 3000
  publish = "dist"
